/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R360ShootRouteImport } from './routes/360-shoot'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SellWithUsRouteImport } from './routes/sell-with-us'
import { Route as SellerPerksRouteImport } from './routes/seller-perks'
import { Route as SoldRouteImport } from './routes/sold'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdviceIndexRouteImport } from './routes/advice.index'
import { Route as AdviceSlugRouteImport } from './routes/advice.$slug'
import { Route as BuildersIndexRouteImport } from './routes/builders.index'
import { Route as BuildersIdRouteImport } from './routes/builders.$id'
import { Route as CollectionsPersonaRouteImport } from './routes/collections.$persona'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as ExploreCityRouteImport } from './routes/explore.$city'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R360ShootRoute = R360ShootRouteImport.update({
  id: '/360-shoot',
  path: '/360-shoot',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SellWithUsRoute = SellWithUsRouteImport.update({
  id: '/sell-with-us',
  path: '/sell-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerPerksRoute = SellerPerksRouteImport.update({
  id: '/seller-perks',
  path: '/seller-perks',
  getParentRoute: () => rootRouteImport,
} as any)
const SoldRoute = SoldRouteImport.update({
  id: '/sold',
  path: '/sold',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceIndexRoute = AdviceIndexRouteImport.update({
  id: '/advice/',
  path: '/advice/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceSlugRoute = AdviceSlugRouteImport.update({
  id: '/advice/$slug',
  path: '/advice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersIndexRoute = BuildersIndexRouteImport.update({
  id: '/builders/',
  path: '/builders/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersIdRoute = BuildersIdRouteImport.update({
  id: '/builders/$id',
  path: '/builders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsPersonaRoute = CollectionsPersonaRouteImport.update({
  id: '/collections/$persona',
  path: '/collections/$persona',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCityRoute = ExploreCityRouteImport.update({
  id: '/explore/$city',
  path: '/explore/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/360-shoot': typeof R360ShootRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sell-with-us': typeof SellWithUsRoute
  '/seller-perks': typeof SellerPerksRoute
  '/sold': typeof SoldRoute
  '/terms': typeof TermsRoute
  '/advice/$slug': typeof AdviceSlugRoute
  '/builders/$id': typeof BuildersIdRoute
  '/collections/$persona': typeof CollectionsPersonaRoute
  '/explore/$city': typeof ExploreCityRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/advice/': typeof AdviceIndexRoute
  '/builders/': typeof BuildersIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/360-shoot': typeof R360ShootRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sell-with-us': typeof SellWithUsRoute
  '/seller-perks': typeof SellerPerksRoute
  '/sold': typeof SoldRoute
  '/terms': typeof TermsRoute
  '/advice/$slug': typeof AdviceSlugRoute
  '/builders/$id': typeof BuildersIdRoute
  '/collections/$persona': typeof CollectionsPersonaRoute
  '/explore/$city': typeof ExploreCityRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/advice': typeof AdviceIndexRoute
  '/builders': typeof BuildersIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/360-shoot': typeof R360ShootRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sell-with-us': typeof SellWithUsRoute
  '/seller-perks': typeof SellerPerksRoute
  '/sold': typeof SoldRoute
  '/terms': typeof TermsRoute
  '/advice/$slug': typeof AdviceSlugRoute
  '/builders/$id': typeof BuildersIdRoute
  '/collections/$persona': typeof CollectionsPersonaRoute
  '/explore/$city': typeof ExploreCityRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/advice/': typeof AdviceIndexRoute
  '/builders/': typeof BuildersIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/360-shoot'
    | '/about'
    | '/account'
    | '/contact'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/sell-with-us'
    | '/seller-perks'
    | '/sold'
    | '/terms'
    | '/advice/$slug'
    | '/builders/$id'
    | '/collections/$persona'
    | '/explore/$city'
    | '/properties/$id'
    | '/advice/'
    | '/builders/'
    | '/explore/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/360-shoot'
    | '/about'
    | '/account'
    | '/contact'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/sell-with-us'
    | '/seller-perks'
    | '/sold'
    | '/terms'
    | '/advice/$slug'
    | '/builders/$id'
    | '/collections/$persona'
    | '/explore/$city'
    | '/properties/$id'
    | '/advice'
    | '/builders'
    | '/explore'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/360-shoot'
    | '/about'
    | '/account'
    | '/contact'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/sell-with-us'
    | '/seller-perks'
    | '/sold'
    | '/terms'
    | '/advice/$slug'
    | '/builders/$id'
    | '/collections/$persona'
    | '/explore/$city'
    | '/properties/$id'
    | '/advice/'
    | '/builders/'
    | '/explore/'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R360ShootRoute: typeof R360ShootRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SellWithUsRoute: typeof SellWithUsRoute
  SellerPerksRoute: typeof SellerPerksRoute
  SoldRoute: typeof SoldRoute
  TermsRoute: typeof TermsRoute
  AdviceSlugRoute: typeof AdviceSlugRoute
  BuildersIdRoute: typeof BuildersIdRoute
  CollectionsPersonaRoute: typeof CollectionsPersonaRoute
  ExploreCityRoute: typeof ExploreCityRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  AdviceIndexRoute: typeof AdviceIndexRoute
  BuildersIndexRoute: typeof BuildersIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/360-shoot': {
      id: '/360-shoot'
      path: '/360-shoot'
      fullPath: '/360-shoot'
      preLoaderRoute: typeof R360ShootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-with-us': {
      id: '/sell-with-us'
      path: '/sell-with-us'
      fullPath: '/sell-with-us'
      preLoaderRoute: typeof SellWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-perks': {
      id: '/seller-perks'
      path: '/seller-perks'
      fullPath: '/seller-perks'
      preLoaderRoute: typeof SellerPerksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sold': {
      id: '/sold'
      path: '/sold'
      fullPath: '/sold'
      preLoaderRoute: typeof SoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice/': {
      id: '/advice/'
      path: '/advice'
      fullPath: '/advice/'
      preLoaderRoute: typeof AdviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice/$slug': {
      id: '/advice/$slug'
      path: '/advice/$slug'
      fullPath: '/advice/$slug'
      preLoaderRoute: typeof AdviceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders/': {
      id: '/builders/'
      path: '/builders'
      fullPath: '/builders/'
      preLoaderRoute: typeof BuildersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders/$id': {
      id: '/builders/$id'
      path: '/builders/$id'
      fullPath: '/builders/$id'
      preLoaderRoute: typeof BuildersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$persona': {
      id: '/collections/$persona'
      path: '/collections/$persona'
      fullPath: '/collections/$persona'
      preLoaderRoute: typeof CollectionsPersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$city': {
      id: '/explore/$city'
      path: '/explore/$city'
      fullPath: '/explore/$city'
      preLoaderRoute: typeof ExploreCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R360ShootRoute: R360ShootRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SellWithUsRoute: SellWithUsRoute,
  SellerPerksRoute: SellerPerksRoute,
  SoldRoute: SoldRoute,
  TermsRoute: TermsRoute,
  AdviceSlugRoute: AdviceSlugRoute,
  BuildersIdRoute: BuildersIdRoute,
  CollectionsPersonaRoute: CollectionsPersonaRoute,
  ExploreCityRoute: ExploreCityRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  AdviceIndexRoute: AdviceIndexRoute,
  BuildersIndexRoute: BuildersIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
